app/models.py
from app import db
class Task(db.Model):
    id = db.column(db.Integer, primary_key = True)
    title = db.column(db.String(100), nullable = False)
    ststus = db.column(db.String(20), default = "Pending")

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length



class LoginForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[DataRequired(), Length(min=3, max=150)]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired()]
    )
    submit = SubmitField('Login')


class RegisterForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[DataRequired(), Length(min=3, max=150)]
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired()]
    )
    submit = SubmitField('Register')


class TaskForm(FlaskForm):
    title = StringField(
        'Task',
        validators=[DataRequired(), Length(max=100)]
    )
    submit = SubmitField('Save')

app/__init__.py
from flask_wtf import CSRFProtect
from flask import Flask, LoginManager
from flask_sqlalchemy import SQLAlchemy 


db = SQLAlchemy()
login_manager = LoginManager()
csrf = CSRFProtect()                                             # create database object globally

def create_app():
    app = Flask(__name__)

    app.config['SECRET_KEY'] = 'to_do_or_not_to_do'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///site.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'auth.login'

    from app.routes.auth import auth_bp
    from app.routes.tasks import tasks_bp
    app.register_blueprint(auth_bp)
    app.register_blueprint(tasks_bp)

    return app

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, login_required

from app import db
from app.models import User
from app.forms import LoginForm, RegisterForm

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        if User.query.filter_by(username=form.username.data).first():
            flash('Username already exists')
            return redirect(url_for('auth.register'))

        new_user = User(
            username=form.username.data,
            password=generate_password_hash(form.password.data)
        )

        db.session.add(new_user)
        db.session.commit()

        flash('Account created successfully. Please login.')
        return redirect(url_for('auth.login'))

    return render_template('register.html', form = form)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username = form.username.data).first()
        



        if not user or not check_password_hash(user.password, form.password.data):
            flash('Invalid username or password')
            return redirect(url_for('auth.login'))

        login_user(user)
        flash('Logged in successfully')
        return redirect(url_for('tasks.home'))

    return render_template('login.html', form = form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out successfully')
    return redirect(url_for('auth.login'))

app/routes/tasks.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, current_user

from app import db
from app.models import Task
from app.forms import TaskForm


tasks_bp  = Blueprint('tasks', __name__)

@tasks_bp.route('/')
@login_required
def home():
    form = TaskForm()
    tasks = Task.query.filter_by(user_id=current_user.id).all()
    return render_template('tasks.html', tasks=tasks, form = form)


@tasks_bp.route('/add', methods=['POST'])
@login_required
def add_task():
    form = TaskForm()
    if form.validate_on_submit():

        task = Task(title=form.title.data, user_id=current_user.id)
        db.session.add(task)
        db.session.commit()
        flash('Task added successfully')
    return redirect(url_for('tasks.home'))


@tasks_bp.route('/complete/<int:task_id>')
@login_required
def complete_task(task_id):
    task = Task.query.get_or_404(task_id)
    task.status = "Completed"

    db.session.commit()
    flash("task marked as completed.")
    return redirect(url_for('tasks.home'))


@tasks_bp.ropute('/delete/<int:task_id>')
@login_required
def delete_task(task_id):
    task = Task.queryget_or_404(task_id)

    db.session.delete(task)
    db.session.commit()

    flash("task deleted")
    return redirect(url_for('tasks.home'))


@tasks_bp.route('/edit/<int:task_id>', methods=['GET', 'POST'])
@login_required
def edit_task(task_id):
    task = Task.query.get_or_404(task_id)

    # Ownership check
    if task.user_id != current_user.id:
        flash('Unauthorized action')
        return redirect(url_for('tasks.home'))

    form = TaskForm(obj=task)

    if form.validate_on_submit():
        task.title = form.title.data
        db.session.commit()
        flash('Task updated')
        return redirect(url_for('tasks.home'))

    return render_template('edit_task.html', form=form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Document{% endblock %}</title>

    <link href="https://fonts.googleapis.com/css2?family=Cinzel:wght@400;700&display=swap" rel="stylesheet">

    <style>
        body {
            font-family: Cinzel, serif;
            margin: 40 px;
        }
        nav a {
            margin-right: 15px;
            text-decoration: none;
        }
        .flash {
            color:red;
            margin-bottom: 10px;
        }
    </style>
</head>

<body>
    <!-- Navigation bar -->
    <nav>
        {% if current_user.is_authenticated %}
        <span> Welcome, {{ current_user.username }}! </span>
        <a href = "{{ url_for('tasks.home') }}" >Tasks</a>
        <a href = "{{ url_for('auth.logout') }}">Llogout</a>
        {% else %}
        <a href="{{ url_for(auth.login) }}" >Login</a>
        <a href="{{ url_for('auth.register') }}" >register</a>
        {% endfor %}
    </nav>
    
    <hr>
    <!-- Flash Messages-->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
                <div class = "flash">{{ message }}</div>
            {% endfor %}
        {% endif %}
    {% endwith %}

    <!-- Main Content -->
    {% block content %}{% endblock %}
</body>
</html>

app/templates/edit_task.html
{% extends "base.html" %}

{% block title %}Edit Task{% endblock %}

{% block content %}
<h2>Edit Task</h2>

<form method="POST">
    {{ form.hidden_tag() }}

    <div>
        {{ form.title.label }}<br>
        {{ form.title() }}
    </div>

    <br>

    {{ form.submit() }}
</form>

<p>
    <a href="{{ url_for('tasks.home') }}">Back to tasks</a>
</p>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
<h2>Login</h2>

<form method="POST">
    {{ form.hidden_tag() }}

    <div>
        {{ form.username.label }}<br>
        {{ form.username() }}
    </div>

    <br>

    <div>
        {{ form.password.label }}<br>
        {{ form.password() }}
    </div>

    <br>

    {{ form.submit() }}
</form>

<p>
    Don’t have an account?
    <a href="{{ url_for('auth.register') }}">Register here</a>
</p>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<h2>Register</h2>

<form method="POST">
    {{ form.hidden_tag() }}

    <div>
        {{ form.username.label }}<br>
        {{ form.username() }}
    </div>

    <br>

    <div>
        {{ form.password.label }}<br>
        {{ form.password() }}
    </div>

    <br>

    {{ form.submit() }}
</form>

<p>
    Already have an account?
    <a href="{{ url_for('auth.login') }}">Login here</a>
</p>
{% endblock %}

app/templates/tasks.html
{% extends "base.html" %}

{% block title %}My Tasks{% endblock %}

{% block content %}
<h2>My Tasks</h2>

<!-- Add Task Form -->
<form method="POST" action="{{ url_for('tasks.add_task') }}">
    {{ form.hidden_tag() }}
    {{ form.title() }}
    {{ form.submit() }}
</form>

<br>

<!-- Task List -->
{% if tasks %}
    <ul>
        {% for task in tasks %}
            <li>
                {{ task.title }} —
                <strong>{{ task.status }}</strong>

                {% if task.status != 'Completed' %}
                    <a href="{{ url_for('tasks.complete_task', task_id=task.id) }}">
                        Complete
                    </a>
                {% endif %}

                 <a href="{{ url_for('tasks.edit_task', task_id=task.id) }}">
                    Edit
                </a>

                <a href="{{ url_for('tasks.delete_task', task_id=task.id) }}">
                    Delete
                </a>
                
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No tasks yet. Add one above 👆</p>
{% endif %}
{% endblock %}